server:
  port: 9999
 
spring:
  profiles:
    active: "prod"
  main:
    banner-mode: "off"
   
---    
spring:
  profiles: prod
  datasource:
        url: jdbc:mysql://isbg.ckqz4zbtwhi3.us-west-1.rds.amazonaws.com:3306/isbg
        username: master
        password: 51g35ISBG
        driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none      
     
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 860501104882-sk9djrlq4u1safvm9lkhk60sgejhvnfq.apps.googleusercontent.com
            client-secret: vUYMM9qOyCIb2kdVjHfIFD3r
         
  main:
    banner-mode: "off"
  resources:
    static-locations:
    - classpath:/static/